### ISSUE TITLE
Will not generate code, says it has something to do with dependencies.

### ISSUE THREAD

**Issue by Mahnez** [redstonedesigner/code-generator#2]
I tried to use it but all it does is spew out an error message about dependencies.

**Comment by redstonedesigner** [comment]
I don't understand why that would be the case, could you copy-paste the error you receive?

Thanks,
redstonedesigner

**Comment by redstonedesigner** [comment]
Apologies, I've just checked over the issue and I believe I've patched it.  Could you try again for me please?

Thanks,
redstonedesigner

**Comment by Mahnez** [comment]
For sure! Sorry about the delay, I didn't pay attention to my E-mails.

**Comment by Mahnez** [comment]
It works!
